version: '3.9'

services:
  backend:
    image: learningmanagementsystem.api
    build:
      context: .
      dockerfile: LearningManagementSystem.Api/Dockerfile
    container_name: lms-backend
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=lms_db;user=root;password=123456
      - Storage__Endpoint=storage:9000
      - Storage__AccessKey=myadmin
      - Storage__SecretKey=mystrongpassword123
      - Storage__WithSSL=false
    depends_on:
      - mysql
      - storage
    networks:
      - lms-network

  mysql:
    image: mysql:8.0
    container_name: lms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lms_db
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: lms_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lms-network
        
  storage:
    image: quay.io/minio/minio
    container_name: lms-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: myadmin
      MINIO_ROOT_PASSWORD: mystrongpassword123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  mysql_data:
  minio_data:
